/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents/$agentId/index'
import { Route as AgentsAgentIdRunsRunIdRouteImport } from './routes/agents/$agentId/runs/$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/agents/$agentId/',
  path: '/agents/$agentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRunsRunIdRoute = AgentsAgentIdRunsRunIdRouteImport.update({
  id: '/agents/$agentId/runs/$runId',
  path: '/agents/$agentId/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
  '/agents/$agentId/runs/$runId': typeof AgentsAgentIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
  '/agents/$agentId/runs/$runId': typeof AgentsAgentIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
  '/agents/$agentId/runs/$runId': typeof AgentsAgentIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents/$agentId/' | '/agents/$agentId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents/$agentId' | '/agents/$agentId/runs/$runId'
  id: '__root__' | '/' | '/agents/$agentId/' | '/agents/$agentId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
  AgentsAgentIdRunsRunIdRoute: typeof AgentsAgentIdRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/runs/$runId': {
      id: '/agents/$agentId/runs/$runId'
      path: '/agents/$agentId/runs/$runId'
      fullPath: '/agents/$agentId/runs/$runId'
      preLoaderRoute: typeof AgentsAgentIdRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
  AgentsAgentIdRunsRunIdRoute: AgentsAgentIdRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
