export type AnalyticsIdentifier =
  | "AllHostsPage"
  | "Annotations"
  | "April Fools"
  | "Breadcrumb"
  | "Configure"
  | "DistroSettings"
  | "HostPage"
  | "JobLogs"
  | "Navbar"
  | "Patch"
  | "Polling"
  | "PreferencesPages"
  | "ProjectHealthPages"
  | "ProjectPatches"
  | "ProjectSettings"
  | "Shortcut"
  | "SpawnPages"
  | "Task"
  | "TaskQueue"
  | "UserPatches"
  | "Version";
