apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spruce
  title: Spruce
  annotations:
    evergreen/project-id: 65f08ccac9ec449f57b4015d
  links:
    - url: https://docs.devprod.prod.corp.mongodb.com/evergreen
      title: Docs on Pine
      icon: dashboard
    - url: https://github.com/evergreen-ci/ui/tree/main/apps/spruce
      title: evergreen-ci/ui Spruce
      icon: github
spec:
  type: website
  owner: group:10gen-evergreen-ui
  lifecycle: production
  system: evergreen
  dependsOn:
    - component:default/Sentry
    - component:default/Honeycomb
    - component:default/evergreen-backend
  consumesApis:
    - evergreen-graphql-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: parsley
  title: Parsley
  description: Evergreen log viewer
  annotations:
    evergreen/project-id: 65f08ccac9ec449f57b4015d
  links:
    - url: https://docs.devprod.prod.corp.mongodb.com/evergreen
      title: Docs on Pine
      icon: dashboard
    - url: https://github.com/evergreen-ci/ui/tree/main/apps/parsley
      title: evergreen-ci/ui Parsley
      icon: github
spec:
  type: website
  owner: group:10gen-evergreen-ui
  lifecycle: production
  system: evergreen
  dependsOn:
    - component:sage
    - component:default/Sentry
    - component:default/Honeycomb
    - component:default/evergreen-backend
  consumesApis:
    - evergreen-graphql-api

