#!/usr/bin/env node
// Regenerates src/components/Icon/glyphs.ts (Via ships no runtime
// glyph-name list to import). Run from packages/lib after bumping
// @via-ds/icons or adding a local icon.
import { readdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const libRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const viaGlyphsDir = join(libRoot, "node_modules/@via-ds/icons/dist/glyphs");
const localIconsIndex = join(libRoot, "src/components/Icon/icons/index.tsx");
const outFile = join(libRoot, "src/components/Icon/glyphs.ts");

const viaNames = readdirSync(viaGlyphsDir)
  .filter((f) => f.endsWith(".svg.mjs"))
  .map((f) => f.replace(/\.svg\.mjs$/, ""));

const localSource = readFileSync(localIconsIndex, "utf8");
const localNames = [...localSource.matchAll(/export \{ (\w+) \} from/g)].map(
  (m) => m[1],
);

const names = [...new Set([...viaNames, ...localNames])].sort();

const body = names.map((n) => `  ${n}: true,`).join("\n");
const output = `// Auto-generated by scripts/update-glyphs.mjs. Regenerate after bumping
// @via-ds/icons or adding a local icon (run from packages/lib).
export const glyphs = {
${body}
} as const;
`;

writeFileSync(outFile, output);
console.log(
  `Wrote ${outFile}: ${viaNames.length} via glyphs + ${localNames.length} local = ${names.length} entries.`,
);
