import {
  AdminSettingsQuery,
  BannerTheme,
  FeedbackRule,
  FinderVersion,
  HostAllocatorVersion,
  OverallocatedRule,
  PriorityLevel,
  RoundingRule,
} from "gql/generated/types";

export const adminSettings: NonNullable<AdminSettingsQuery["adminSettings"]> = {
  amboy: {
    groupBackgroundCreateFrequencyMinutes: 1,
    groupDefaultWorkers: 1,
    groupPruneFrequencyMinutes: 1,
    groupTTLMinutes: 1,
    localStorage: 1,
    lockTimeoutMinutes: 1,
    name: "amboy",
    namedQueues: [
      {
        lockTimeoutSeconds: 1,
        name: "named.queue.1",
        numWorkers: 1,
        regexp: "",
        sampleSize: 1,
      },
    ],
    poolSizeLocal: 1,
    poolSizeRemote: 1,
    retry: {
      maxCapacity: 1,
      maxRetryAttempts: 1,
      maxRetryTimeSeconds: 1,
      numWorkers: 1,
      retryBackoffSeconds: 1,
      staleRetryingMonitorIntervalSeconds: 1,
    },
    sampleSize: 1,
    singleName: "single",
  },
  amboyDB: {
    database: "amboy-db-name",
    url: "amboy-db-url",
  },
  api: {
    corpUrl: "http://corp.example.com",
    httpListenAddr: "http://localhost:8080",
    url: "http://localhost:9090",
  },
  banner: "Hello",
  bannerTheme: BannerTheme.Information,
  disabledGQLQueries: ["query1", "query2"],
  hostInit: {
    cloudStatusBatchSize: 1,
    hostThrottle: 1,
    maxTotalDynamicHosts: 1,
    provisioningThrottle: 1,
  },
  loggerConfig: {
    buffer: {
      count: 1,
      durationSeconds: 1,
      incomingBufferFactor: 1,
      useAsync: true,
    },
    defaultLevel: PriorityLevel.Emergency,
    logkeeperURL: "logkeeper-url",
    redactKeys: ["secret", "key"],
    thresholdLevel: PriorityLevel.Info,
  },
  notify: {
    bufferIntervalSeconds: 1,
    bufferTargetPerInterval: 1,
    ses: {
      senderAddress: "evg-sender",
    },
  },
  repotracker: {
    maxConcurrentRequests: 1,
    maxRepoRevisionsToSearch: 1,
    numNewRepoRevisionsToFetch: 1,
  },
  scheduler: {
    acceptableHostIdleTimeSeconds: 1,
    cacheDurationSeconds: 1,
    commitQueueFactor: 1,
    expectedRuntimeFactor: 1,
    futureHostFraction: 1,
    generateTaskFactor: 1,
    groupVersions: false,
    hostAllocator: HostAllocatorVersion.Utilization,
    hostAllocatorFeedbackRule: FeedbackRule.NoFeedback,
    hostAllocatorRoundingRule: RoundingRule.Up,
    hostsOverallocatedRule: OverallocatedRule.Ignore,
    mainlineTimeInQueueFactor: 1,
    numDependentsFactor: 1,
    patchFactor: 1,
    patchTimeInQueueFactor: 1,
    stepbackTaskFactor: 1,
    targetTimeSeconds: 1,
    taskFinder: FinderVersion.Parallel,
    translateProjectCacheBytesLimit: 1,
    translateProjectCacheTTLSeconds: 1,
    translateProjectConcurrencyLimit: 1,
  },
  taskLimits: {
    maxConcurrentLargeParserProjectTasks: 1,
    maxDailyAutomaticRestarts: 1,
    maxDegradedModeConcurrentLargeParserProjectTasks: 1,
    maxDegradedModeParserProjectSize: 1,
    maxExecTimeoutSecs: 1,
    maxGenerateTaskJSONSize: 1,
    maxHourlyPatchTasks: 1,
    maxIncludesPerVersion: 1,
    maxParserProjectSize: 1,
    maxPendingGeneratedTasks: 1,
    maxScheduledTasksPerDistro: 1,
    maxTaskExecution: 1,
    maxTasksPerVersion: 1,
  },
  triggers: {
    generateTaskDistro: "archlinux-test",
  },
  ui: {
    betaFeatures: {
      __typename: "BetaFeatures",
    },
    cacheTemplates: true,
    corsOrigins: ["http://example.com"],
    csrfKey: "csrf-secret-key",
    defaultProject: "default",
    fileStreamingContentTypes: ["application/json"],
    httpListenAddr: "http://localhost:8081",
    loginDomain: "example.com",
    parsleyUrl: "http://parsley.example.com",
    secret: "supersecret",
    stagingEnvironment: "staging",
    uiv2Url: "http://uiv2.example.com",
    url: "http://ui.example.com",
    userVoice: "http://uservoice.example.com",
  },
};
