import {
  AdminSettings,
  BannerTheme,
  FeedbackRule,
  FinderVersion,
  HostAllocatorVersion,
  OverallocatedRule,
  PriorityLevel,
  RoundingRule,
} from "gql/generated/types";

export const adminSettings: AdminSettings = {
  banner: "Hello",
  bannerTheme: BannerTheme.Information,
  hostInit: {
    cloudStatusBatchSize: 1,
    hostThrottle: 1,
    maxTotalDynamicHosts: 1,
    provisioningThrottle: 1,
  },
  notify: {
    ses: {
      senderAddress: "evg-sender",
    },
    bufferIntervalSeconds: 1,
    bufferTargetPerInterval: 1,
  },
  podLifecycle: {
    maxParallelPodRequests: 1,
    maxPodDefinitionCleanupRate: 1,
    maxSecretCleanupRate: 1,
  },
  repotracker: {
    maxConcurrentRequests: 1,
    maxRepoRevisionsToSearch: 1,
    numNewRepoRevisionsToFetch: 1,
  },
  scheduler: {
    acceptableHostIdleTimeSeconds: 1,
    cacheDurationSeconds: 1,
    commitQueueFactor: 1,
    expectedRuntimeFactor: 1,
    futureHostFraction: 1,
    generateTaskFactor: 1,
    groupVersions: false,
    hostAllocator: HostAllocatorVersion.Utilization,
    hostAllocatorFeedbackRule: FeedbackRule.NoFeedback,
    hostAllocatorRoundingRule: RoundingRule.Up,
    hostsOverallocatedRule: OverallocatedRule.Ignore,
    mainlineTimeInQueueFactor: 1,
    numDependentsFactor: 1,
    patchFactor: 1,
    patchTimeInQueueFactor: 1,
    stepbackTaskFactor: 1,
    targetTimeSeconds: 1,
    taskFinder: FinderVersion.Parallel,
  },
  serviceFlags: {
    agentStartDisabled: true,
    alertsDisabled: true,
    backgroundReauthDisabled: true,
    backgroundStatsDisabled: true,
    cacheStatsEndpointDisabled: true,
    cacheStatsJobDisabled: true,
    checkBlockedTasksDisabled: true,
    cliUpdatesDisabled: true,
    cloudCleanupDisabled: true,
    debugSpawnHostDisabled: true,
    degradedModeDisabled: true,
    elasticIPsDisabled: true,
    emailNotificationsDisabled: true,
    eventProcessingDisabled: true,
    githubPRTestingDisabled: true,
    githubStatusAPIDisabled: true,
    hostAllocatorDisabled: true,
    hostInitDisabled: true,
    jiraNotificationsDisabled: true,
    jwtTokenForCLIDisabled: true,
    largeParserProjectsDisabled: true,
    monitorDisabled: true,
    podAllocatorDisabled: true,
    podInitDisabled: true,
    releaseModeDisabled: true,
    repotrackerDisabled: true,
    schedulerDisabled: true,
    slackNotificationsDisabled: true,
    sleepScheduleDisabled: true,
    staticAPIKeysDisabled: true,
    systemFailedTaskRestartDisabled: true,
    taskDispatchDisabled: true,
    taskLoggingDisabled: true,
    taskReliabilityDisabled: true,
    unrecognizedPodCleanupDisabled: true,
    useGitForGitHubFilesDisabled: true,
    webhookNotificationsDisabled: true,
  },
  taskLimits: {
    maxConcurrentLargeParserProjectTasks: 1,
    maxDailyAutomaticRestarts: 1,
    maxDegradedModeConcurrentLargeParserProjectTasks: 1,
    maxDegradedModeParserProjectSize: 1,
    maxExecTimeoutSecs: 1,
    maxGenerateTaskJSONSize: 1,
    maxHourlyPatchTasks: 1,
    maxIncludesPerVersion: 1,
    maxParserProjectSize: 1,
    maxPendingGeneratedTasks: 1,
    maxTaskExecution: 1,
    maxTasksPerVersion: 1,
  },
  amboy: {
    name: "amboy",
    singleName: "single",
    poolSizeLocal: 1,
    poolSizeRemote: 1,
    localStorage: 1,
    groupDefaultWorkers: 1,
    groupBackgroundCreateFrequencyMinutes: 1,
    groupPruneFrequencyMinutes: 1,
    groupTTLMinutes: 1,
    lockTimeoutMinutes: 1,
    sampleSize: 1,
    retry: {
      numWorkers: 1,
      maxCapacity: 1,
      maxRetryAttempts: 1,
      maxRetryTimeSeconds: 1,
      retryBackoffSeconds: 1,
      staleRetryingMonitorIntervalSeconds: 1,
    },
    namedQueues: [
      {
        name: "named.queue.1",
        regexp: "",
        numWorkers: 1,
        sampleSize: 1,
        lockTimeoutSeconds: 1,
      },
    ],
  },
  amboyDB: {
    url: "amboy-db-url",
    database: "amboy-db-name",
  },
  loggerConfig: {
    buffer: {
      useAsync: true,
      durationSeconds: 1,
      count: 1,
      incomingBufferFactor: 1,
    },
    defaultLevel: PriorityLevel.Emergency,
    thresholdLevel: PriorityLevel.Info,
    logkeeperURL: "logkeeper-url",
    redactKeys: ["secret", "key"],
  },
  triggers: {
    generateTaskDistro: "archlinux-test",
  },
  api: {
    httpListenAddr: "http://localhost:8080",
    url: "http://localhost:9090",
    corpUrl: "http://corp.example.com",
  },
  ui: {
    url: "http://ui.example.com",
    helpUrl: "http://help.example.com",
    uiv2Url: "http://uiv2.example.com",
    parsleyUrl: "http://parsley.example.com",
    httpListenAddr: "http://localhost:8081",
    secret: "supersecret",
    defaultProject: "default",
    corsOrigins: ["http://example.com"],
    fileStreamingContentTypes: ["application/json"],
    loginDomain: "example.com",
    userVoice: "http://uservoice.example.com",
    csrfKey: "csrf-secret-key",
    cacheTemplates: true,
    stagingEnvironment: "staging",
    betaFeatures: {
      parsleyAIEnabled: true,
    },
  },
  disabledGQLQueries: ["query1", "query2"],
};
