import { TaskStatus } from "@evg-ui/lib/types/task";
import { TestStatus } from "@evg-ui/lib/types/test";
import { Requester } from "constants/requesters";
import { GroupedTask, TaskHistoryTask } from "./types";

const emptyTests = {
  testResults: [],
};

export const tasks: TaskHistoryTask[] = [
  {
    activated: true,
    canRestart: true,
    canSchedule: false,
    canSetPriority: false,
    displayStatus: TaskStatus.Succeeded,
    execution: 0,
    id: "a",
    ingestTime: new Date("2025-04-03T10:22:13Z"),
    order: 100,
    requester: Requester.Gitter,
    revision: "aef363719d0287e92cd83749a827bae",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: A",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: true,
    canRestart: true,
    canSchedule: false,
    canSetPriority: false,
    displayStatus: TaskStatus.WillRun,
    execution: 1,
    id: "b",
    ingestTime: new Date("2025-04-03T10:21:13Z"),
    order: 99,
    requester: Requester.Gitter,
    revision: "b",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: B",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: false,
    canRestart: false,
    canSchedule: true,
    canSetPriority: false,
    displayStatus: TaskStatus.Unscheduled,
    execution: 0,
    id: "c",
    ingestTime: new Date("2025-04-03T10:20:13Z"),
    order: 98,
    requester: Requester.Gitter,
    revision: "ce135c28ba11e9189cae",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: C",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: true,
    canRestart: true,
    canSchedule: false,
    canSetPriority: false,
    displayStatus: TaskStatus.SetupFailed,
    execution: 0,
    id: "d",
    ingestTime: new Date("2025-04-02T10:22:13Z"),
    order: 97,
    requester: Requester.Gitter,
    revision: "d",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: D",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: false,
    canRestart: true,
    canSchedule: true,
    canSetPriority: false,
    displayStatus: TaskStatus.Unscheduled,
    execution: 0,
    id: "e",
    ingestTime: new Date("2025-04-02T10:21:13Z"),
    order: 96,
    requester: Requester.Gitter,
    revision: "e",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: E",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: true,
    canRestart: true,
    canSchedule: false,
    canSetPriority: false,
    displayStatus: TaskStatus.Failed,
    execution: 0,
    id: "f",
    ingestTime: new Date("2025-04-01T10:22:13Z"),
    order: 95,
    requester: Requester.Gitter,
    revision: "f",
    tests: {
      testResults: [
        {
          id: "e2e_test_id",
          logs: { urlParsley: "a-parsley-url.mongodb.com" },
          status: TestStatus.Fail,
          testFile: "e2e_test",
        },
      ],
    },
    version: {
      id: "version_id",
      message: "DEVPROD-1234: F",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: false,
    canRestart: false,
    canSchedule: true,
    canSetPriority: false,
    displayStatus: TaskStatus.Unscheduled,
    execution: 0,
    id: "g",
    ingestTime: new Date("2025-04-01T10:21:13Z"),
    order: 94,
    requester: Requester.Gitter,
    revision: "g",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: G",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: false,
    canRestart: false,
    canSchedule: true,
    canSetPriority: false,
    displayStatus: TaskStatus.Unscheduled,
    execution: 0,
    id: "h",
    ingestTime: new Date("2025-04-01T10:20:13Z"),
    order: 93,
    requester: Requester.Gitter,
    revision: "h",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: H",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: false,
    canRestart: false,
    canSchedule: true,
    canSetPriority: false,
    displayStatus: TaskStatus.Unscheduled,
    execution: 0,
    id: "i",
    ingestTime: new Date("2025-04-01T10:18:13Z"),
    order: 92,
    requester: Requester.Gitter,
    revision: "i",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: I",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: true,
    canRestart: true,
    canSchedule: false,
    canSetPriority: false,
    displayStatus: TaskStatus.KnownIssue,
    execution: 3,
    id: "j",
    ingestTime: new Date("2025-03-30T10:22:13Z"),
    order: 91,
    requester: Requester.Gitter,
    revision: "j",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: J",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
  {
    activated: true,
    canRestart: true,
    canSchedule: false,
    canSetPriority: false,
    displayStatus: TaskStatus.SystemFailed,
    execution: 0,
    id: "k",
    ingestTime: new Date("2025-03-29T10:22:13Z"),
    order: 90,
    requester: Requester.Gitter,
    revision: "k",
    tests: emptyTests,
    version: {
      id: "version_id",
      message: "DEVPROD-1234: K",
      user: {
        displayName: "Evergreen Admin",
        id: "admin",
      },
    },
  },
];

export const collapsedGroupedTasks: GroupedTask[] = [
  {
    commitCardRef: null,
    date: tasks[0].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[0],
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[1],
  },
  {
    commitCardRef: null,
    date: null,
    inactiveTasks: [tasks[2]],
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: null,
    date: tasks[3].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[3],
  },
  {
    commitCardRef: null,
    date: null,
    inactiveTasks: [tasks[4]],
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: null,
    date: tasks[5].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[5],
  },
  {
    commitCardRef: null,
    date: null,
    inactiveTasks: [tasks[6], tasks[7], tasks[8]],
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: null,
    date: tasks[9].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[9],
  },
  {
    commitCardRef: null,
    date: tasks[10].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[10],
  },
];

export const expandedGroupedTasks: GroupedTask[] = [
  {
    commitCardRef: null,
    date: tasks[0].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[0],
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[1],
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[2],
  },
  {
    commitCardRef: null,
    date: tasks[3].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[3],
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[4],
  },
  {
    commitCardRef: null,
    date: tasks[5].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[5],
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[6],
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[7],
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[8],
  },
  {
    commitCardRef: null,
    date: tasks[9].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[9],
  },
  {
    commitCardRef: null,
    date: tasks[10].ingestTime!,
    inactiveTasks: null,
    isMatching: false,
    task: null,
  },
  {
    commitCardRef: { current: null },
    date: null,
    inactiveTasks: null,
    isMatching: true,
    task: tasks[10],
  },
];
