import { GetFormSchema } from "components/SpruceForm";
import widgets from "components/SpruceForm/Widgets";
import { ProjectType } from "../utils";

export const getFormSchema = (
  projectType: ProjectType,
): ReturnType<GetFormSchema> => ({
  fields: {},
  schema: {
    definitions: {
      filterArray: {
        default: [],
        items: {
          properties: {
            caseSensitive: {
              default: false,
              oneOf: [
                {
                  enum: [false],
                  title: "Insensitive",
                  type: "boolean" as const,
                },
                {
                  enum: [true],
                  title: "Sensitive",
                  type: "boolean" as const,
                },
              ],
              title: "Case",
              type: "boolean" as const,
            },
            description: {
              default: "",
              title: "Description",
              type: "string" as const,
            },
            exactMatch: {
              default: true,
              oneOf: [
                {
                  enum: [true],
                  title: "Exact",
                  type: "boolean" as const,
                },
                {
                  enum: [false],
                  title: "Inverse",
                  type: "boolean" as const,
                },
              ],
              title: "Match",
              type: "boolean" as const,
            },
            expression: {
              default: "",
              format: "validRegex",
              minLength: 1,
              title: "Filter Expression",
              type: "string" as const,
            },
          },
          type: "object" as const,
        },
        title: "",
        type: "array" as const,
      },
    },
    properties: {
      parsleyFilters: { $ref: "#/definitions/filterArray" },
      parsleyFiltersTitle: {
        title: "Parsley Filters",
        type: "null",
      },
      ...(projectType === ProjectType.AttachedProject && {
        repoData: {
          properties: {
            parsleyFilters: { $ref: "#/definitions/filterArray" },
          },
          title: "Repo Filters",
          type: "object" as const,
        },
      }),
    },
    type: "object" as const,
  },
  uiSchema: {
    parsleyFilters: {
      items: {
        caseSensitive: {
          "ui:aria-controls": ["case-insensitive", "case-sensitive"],
          "ui:data-cy": "parsley-filter-case-sensitivity",
          "ui:sizeVariant": "xsmall",
          "ui:widget": widgets.SegmentedControlWidget,
        },
        description: {
          "ui:widget": "textarea",
        },
        exactMatch: {
          "ui:aria-controls": ["exact-match", "inverse-match"],
          "ui:data-cy": "parsley-filter-match-type",
          "ui:sizeVariant": "xsmall",
          "ui:widget": widgets.SegmentedControlWidget,
        },
        expression: {
          "ui:data-cy": "parsley-filter-expression",
          "ui:widget": "textarea",
        },
        "ui:data-cy": "parsley-filter",
        "ui:displayTitle": "New Parsley Filter",
        "ui:label": false,
      },
      "ui:addButtonText": "Add filter",
      "ui:data-cy": "parsley-filter-list",
      "ui:description":
        "These filters will be available by default in the Parsley log viewer for any logs generated by this project.",
      "ui:orderable": false,
      "ui:useExpandableCard": true,
    },
    parsleyFiltersTitle: {
      "ui:sectionTitle": true,
    },
    repoData: {
      parsleyFilters: {
        items: {
          caseSensitive: {
            "ui:sizeVariant": "xsmall",
            "ui:widget": widgets.SegmentedControlWidget,
          },
          description: {
            "ui:widget": "textarea",
          },
          exactMatch: {
            "ui:sizeVariant": "xsmall",
            "ui:widget": widgets.SegmentedControlWidget,
          },
          expression: {
            "ui:widget": "textarea",
          },
        },
        "ui:fullWidth": true,
        "ui:placeholder": "Repo has no filters defined.",
        "ui:readonly": true,
        "ui:showLabel": false,
        "ui:useExpandableCard": true,
      },
    },
  },
});
