name: "Parsley Chromatic"

on: pull_request

jobs:
  parsley-chromatic:
    name: Parsley Chromatic
    environment: CI   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
        # Taken from docs for pull request configuration
        env:
          CHROMATIC_BRANCH: ${{ github.event.pull_request.head.ref || github.ref_name }}
          CHROMATIC_SHA: ${{ github.event.pull_request.head.sha || github.ref }}
          CHROMATIC_SLUG: ${{ github.repository }}

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0

      - name: Install dependencies
        run: yarn install

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: apps/parsley
          buildScriptName: storybook:build
          # https://www.chromatic.com/docs/github-actions/#forked-repositories
          projectToken: ${{ secrets.CHROMATIC_PARSLEY_TOKEN }} # Likely won't work due to fork restrictions
          autoAcceptChanges: "main"
